- sdk/Pulumi.Tests/Core/OutputTests.cs
- sdk/Pulumi/Exceptions/LogException.cs
Last bits from
- https://github.com/pulumi/pulumi/pull/11307
- https://github.com/pulumi/pulumi/pull/11624
> Sync with dotnet SDK from pulumi/pulumi

- CHANGELOG_PENDING.md
- sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
- sdk/Pulumi.Automation/LocalWorkspace.cs
- sdk/Pulumi.Automation/Pulumi.Automation.xml
- sdk/Pulumi.Automation/Workspace.cs
- sdk/Pulumi.Automation/WorkspaceStack.cs
Dotnet fix for https://github.com/pulumi/pulumi/issues/11936
> Add tag methods

- .github/workflows/pr.yml
- .github/workflows/release-sdk.yml
- CHANGELOG_PENDING.md
- sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
- sdk/Pulumi.Automation/LocalWorkspace.cs
- sdk/Pulumi.Automation/WhoAmIResult.cs
Fixes https://github.com/pulumi/pulumi-dotnet/issues/116
> Add Url and Organizations to WhoAmI

- CHANGELOG_PENDING.md
- sdk/Pulumi.Automation/PendingCreateValue.cs
- sdk/Pulumi.Automation/RefreshOptions.cs
- sdk/Pulumi.Automation/WorkspaceStack.cs
[Related Issue](https://github.com/pulumi/pulumi/issues/11336)
Exposes additional options to the Automation API to the [Pulumi refresh](https://www.pulumi.com/docs/reference/cli/pulumi_refresh/) command
> Expose additional options to Refresh command

- CHANGELOG_PENDING.md
- sdk/Pulumi.Tests/Core/ResourceArgsTests.cs
- sdk/Pulumi/Core/Output.cs
- sdk/Pulumi/Pulumi.xml
- sdk/Pulumi/Resources/InputArgs.cs
Fixes https://github.com/pulumi/pulumi-dotnet/issues/142
> Fix serialization of secret json resource arguments

- CHANGELOG.md
- CHANGELOG_PENDING.md
Also fix the changelog and changelog_pending being out of date
> Prepare v3.56.1

- CHANGELOG_PENDING.md
- proto/pulumi/converter.proto
- proto/pulumi/language.proto
- proto/pulumi/plugin.proto
- proto/pulumi/provider.proto
- proto/pulumi/resource.proto
- proto/pulumi/testing/language.proto
- sdk/Pulumi/Converter/Converter.cs
This PR syncs proto file changes from pulumi/pulumi and adds `Args: string[]` to the `ConvertProgramRequest`
> [converter/sdk] Add `Args: string[]` to ConvertProgramRequest

- .changes/unreleased/Bug Fixes-186.yaml
- sdk/Pulumi.Automation/LocalWorkspace.cs
Addresses https://github.com/pulumi/pulumi-dotnet/issues/185
> Fix `--remote-git-username` argument

- .github/workflows/pr.yml
Publish a dev SDK for pulumi-dotnet which we can consume later for pre-release testing.
> Publish dev SDK

- .changes/unreleased/Bug Fixes-262.yaml
- sdk/Pulumi.Tests/Provider/ProviderTests.cs
- sdk/Pulumi/Config.cs
- sdk/Pulumi/Resources/CustomTimeouts.cs
Fixes https://github.com/pulumi/pulumi-dotnet/issues/261.
> Use InvariantCulture for parsing numbers from config

- .changes/unreleased/Improvements-270.yaml
- .changes/unreleased/Improvements-277.yaml
Make the changelog entries follow the guidelines we follow in pulumi/pulumi as well.
> improve changelog entries

- .changes/unreleased/Improvements-288.yaml
- .gitignore
- integration_tests/go.mod
- integration_tests/go.sum
- proto/pulumi/language.proto
- proto/pulumi/provider.proto
- proto/pulumi/resource.proto
- pulumi-language-dotnet/go.mod
- pulumi-language-dotnet/go.sum
- pulumi-language-dotnet/main.go
- sdk/Pulumi/Pulumi.xml
Update pulumi/pulumi to 3.121 and add a noop `RuntimeOptionsPrompts`.
> Update pulumi/pulumi to 3.121

- sdk/Pulumi.Automation/Pulumi.Automation.xml
- sdk/Pulumi/Pulumi.xml
Noticed some changes to these files during local development that hadn't been committed. This change does that.
> Update .xml doc files

- proto/pulumi/language.proto
- proto/pulumi/provider.proto
- proto/pulumi/resource.proto
Update proto files to the latest published from pulumi to get access to new protocol features such as invoke transforms. (Similar to #233).
> Update proto files

- .github/workflows/pr.yml
Fix some 'if' checks to be more general, and some job descriptions that incorrectly said they were installing .NET 6.
> Generalize and fix some workflow code

- .changes/unreleased/bug-fixes-420.yaml
- sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
- sdk/Pulumi.Tests/Deployment/InlineDeploymentTests.cs
- sdk/Pulumi/Deployment/Deployment.Runner.cs
- sdk/Pulumi/Deployment/Deployment_Inline.cs
- sdk/Pulumi/Deployment/IRunner.cs
- sdk/Pulumi/Provider/Provider.cs
Adds an await for inline deployments
@Frassle  As dicussed over slack, new pr since I used the wrong base branch.
> await background tasks in inline deployments

- .github/workflows/pr.yml
- .golangci.yml
- Makefile
- integration_tests/aliases_dotnet_test.go
- integration_tests/integration_dotnet_smoke_test.go
- integration_tests/integration_dotnet_test.go
- integration_tests/integration_util_test.go
- integration_tests/transformations_simple_test.go
- pulumi-language-dotnet/language_test.go
- pulumi-language-dotnet/main.go
- pulumi-language-dotnet/main_test.go
Copied from pulumi/pulumi repo.
> Lint Go code

- .changes/unreleased/Improvements-580.yaml
- .github/workflows/pr.yml
- sdk/Pulumi.Automation/DestroyOptions.cs
- sdk/Pulumi.Automation/Pulumi.Automation.xml
- sdk/Pulumi.Automation/RefreshOptions.cs
- sdk/Pulumi.Automation/WorkspaceStack.cs
Similar change as for https://github.com/pulumi/pulumi/pull/19218 but for dotnet.
Also fix the github workflows, because of course can't make a CI change right in one go.
> Add --run-program to automation api

- pulumi-language-dotnet/main.go
To help with debugging https://github.com/pulumi/pulumi-dotnet/issues/686 and any other similar issues that come up.
> Add a log line to debug list package issues

- .github/workflows/changelog.yml
- mise.toml
Once this PR passes, it's an easy template for getting everything else to work happily.
> Mise for CI: Changelog

- .github/workflows/pr.yml
- .mise.toml
Continuing from #708 for my ops week treat: I'm just going to start removing setup from CI jobs until everything's done by Mise. Hopefully, these implements are small enough to be uncontroversial.
> Mise for CI: format

- .github/workflows/pr.yml
* #708 
* #711 
* #712 
* #713
> Mise for CI: info
