README.md
build/Program.fs

This removes the function `preparePulumiSdkNugetLocally()` which was to build a local nuget package of the Pulumi SDK for testing inside `~/.pulumi-dev/nuget`. This is no longer needed because the integration tests now use a local project reference instead

Remove code that prepares the local nuget package for tests

---

CHANGELOG_PENDING.md
sdk/Pulumi.Automation.Tests/RemoteWorkspaceTests.cs
sdk/Pulumi.Automation/LocalWorkspace.cs
sdk/Pulumi.Automation/LocalWorkspaceOptions.cs
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Automation/RemoteWorkspace.cs
sdk/Pulumi.Automation/RemoteWorkspaceOptions.cs

Automation API support for the `skipInstallDependencies` Deployments API option.
Depends on https://github.com/pulumi/pulumi/pull/11674
Part of https://github.com/pulumi/pulumi/issues/11357

Add `RemoteWorkspaceOptions.SkipInstallDependencies`

---

CHANGELOG_PENDING.md
build/Program.fs
sdk/Pulumi.Automation/Commands/LocalPulumiCmd.cs
sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi.Automation/Serialization/Json/StackSettingsConfigValueJsonConverter.cs
sdk/Pulumi.Automation/Serialization/Json/StringToEnumJsonConverter.cs
sdk/Pulumi.Automation/Serialization/Json/SystemObjectJsonConverter.cs
sdk/Pulumi.Automation/Serialization/LocalSerializer.cs
sdk/Pulumi.Automation/WorkspaceStack.cs
sdk/Pulumi.FSharp/Pulumi.FSharp.fsproj
sdk/Pulumi/Core/Output.cs
sdk/Pulumi/Deployment/Deployment_Config.cs
sdk/Pulumi/Pulumi.csproj

.NET Core 3.1 is out of support on December 13th:
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
We've already stopped testing on .NET Core 3.1, and program gen has been targeting only 6.0 for a while now as well.
This updates the core porjects to only 6.0 as well.
We'll still want to do https://github.com/pulumi/pulumi/pull/11543 in pu/pu to update sdkgen.

Update Pulumi projects to net6.0

---

CHANGELOG_PENDING.md
sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi.Automation/Serialization/LocalSerializer.cs
sdk/Pulumi.FSharp/Pulumi.FSharp.fsproj
sdk/Pulumi/Core/Output.cs
sdk/Pulumi/Pulumi.csproj

This reverts commit e06f542aac0535c85e260d291d0d5df8e496ab83.
This is needed to give providers time to upgrade codegen. We messed up the ordering here thinking we needed to release a 6.0 library, but we can update the provider libraries to 6.0 and have them consume Pulumi.nuget at 3.1.

Revert "Update Pulumi projects to net6.0 (#10)"

---

CHANGELOG_PENDING.md
integration_tests/integration_util_test.go
sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi.FSharp/Pulumi.FSharp.fsproj
sdk/Pulumi/Pulumi.csproj

Update all the SDKs to multi-target netcoreapp3.1 and net6.0. Small change because I had the leftovers of trying to target net6.0 still checked in via `#if` blocks.

Multi-target netcoreapp3.1 and net6.0

---

.github/workflows/pr.yml
CHANGELOG.md
CHANGELOG_PENDING.md
integration_tests/go.mod
integration_tests/go.sum
integration_tests/integration_dotnet_test.go
integration_tests/integration_util_test.go
integration_tests/testprovider/TestProvider.cs
sdk/Pulumi/Provider/Provider.cs

Also make sure we're running integration tests on Windows and MacOS not just linux, and add the Provider test to the test list.

Work around old engines port parsing bug

---

CHANGELOG_PENDING.md
integration_tests/testprovider/TestProvider.cs
sdk/Pulumi/Provider/PropertyValue.cs
sdk/Pulumi/Provider/Provider.cs

Other places in the Pulumi SDK use "Id" not "ID". That is also inline with Microsoft naming guidance.

Consistently case Id in provider interface

---

CHANGELOG.md
CHANGELOG_PENDING.md
sdk/Pulumi.Tests/Mocks/Aliases.cs
sdk/Pulumi.Tests/Mocks/MocksTests.cs
sdk/Pulumi/Deployment/Deployment.cs
sdk/Pulumi/Deployment/Deployment_Prepare.cs
sdk/Pulumi/Deployment/Deployment_RegisterResource.cs
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Resources/Resource.cs

Fixes #14 
Removes `AllAliases` function and instead constructs a`List<Pulumirpc.Alias>` in `PrepareAliases` (linear time) which populates the `RegisterResourceRequest` accordingly:
```csharp
if (prepareResult.SupportsAliasSpec) 
{
request.Aliases.AddRange(prepareResult.Aliases);
}
else 
{
var aliasUrns = prepareResult.Aliases.Select(a => a.Urn);
request.AliasURNs.AddRange(aliasUrns);
}
```
Wasn't exactly sure how to test this other than constructing a lot (=1000) of aliases in `AliasesMocks` and _observe_ that it doesn't just hang for a while. 
All integration tests are succeeding locally except for `TestProvider` but that seems unrelated. Let's see what CI has to say about it.

[sdk] Delegates alias computation to engine

---

.github/workflows/pr.yml
.github/workflows/release-sdk.yml

The Pulumi Staging GitHub App is configured for all repos in the `pulumi` org. Any pulumi updates from staging will result in preview/update comments added on PRs. This adds a lot of unnecessary noise when running automation API tests in this repo.
This PR switches to using the production service like what is used in `pulumi/pulumi`, which avoids these comments since the production Pulumi GitHub App isn't configured for `pulumi` repos.
We'd get a bunch of comments like:
No more comment noise

Run tests on the production service

---

CHANGELOG_PENDING.md
sdk/Pulumi/Deployment/Deployment.cs
sdk/Pulumi/Deployment/Deployment_Prepare.cs

Learnings from implementing go alias delegation to the engine:
- the flag is called "aliasSpecs" not "aliasSpec"
- aliases can also provide a fully qualified URN which can be passed as is to the engine

[sdk] Correctly check for alias support in the engine and map fully specified alias urns

---

CHANGELOG_PENDING.md
sdk/Pulumi/Pulumi.csproj

Pretty much a re-hash of https://github.com/pulumi/pulumi/pull/6793, but for the Pulumi.csproj. Was pointed out in community slack that we'd broken paket again.

Fix dependency on Grpc.Tools

---

CHANGELOG_PENDING.md
sdk/Pulumi/Testing/MockMonitor.cs

Fixes https://github.com/pulumi/pulumi-dotnet/issues/92

Make MockMonitor return true for all features.

---

CHANGELOG_PENDING.md
sdk/Pulumi/Deployment/Deployment_Prepare.cs
sdk/Pulumi/Deployment/Deployment_RegisterResource.cs
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Resources/Resource.cs

Fixes #90 
In order to also bring back the unit tests for `AllAliases`, we need a new feature in `IMocks` that allows us to override the supported features by the resource monitor. Specifically, we need `aliasSpecs` to _not_ be supported in order to test the fallback branch. I will add that in a separate PR

[sdk] Bring back the correct fallback behavior for calculating aliases for older Pulumi engines

---

CHANGELOG_PENDING.md
sdk/Pulumi.Tests/Resources/StackReferenceOutputDetailsTests.cs
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Resources/StackReference.cs
sdk/Pulumi/Resources/StackReferenceOutputDetails.cs

This is the C# equivalent of StackReference.GetOutputDetails
that was added to:
- Go SDK in pulumi/pulumi#12034
- Python SDK in pulumi/pulumi#12071
- Node SDK in pulumi/pulumi#12072
It introduces a GetOutputDetailsAsync method
that returns a StackReferenceOutputDetails promise,
allowing looking at the results without going through an Output type.
**Testing**: As with Node (pulumi/pulumi#12072), C# appears to promote
the entire dictionary to secret if one of the values is secret.
Therefore, this needed separate tests for each case.
Refs pulumi/pulumi#10839, pulumi/pulumi#5035

sdk/StackReference: Add GetOutputDetailsAsync

---

sdk/Pulumi.Tests/Provider/ProviderTests.cs
sdk/Pulumi/Provider/Provider.cs

Reported on community slack.
Because the `ResourceProviderService` wasn't marked as a singleton in the aspnet layer it was being recreated fresh for each grpc request, each fresh creation was then freshly creating the users `Provider` object and so losing any instance state they had set on it.
This also fixed some NPEs in the marshaling layer in the case where `Struct` fields were null.

Fix provider to maintain internal instance state

---

sdk/Pulumi.Tests/Resources/ComponentResourceTests.cs

Adds a test case to verify that a ComponentResource
propagates its Provider and Providers values
to children constructed with that type.
Refs pulumi/pulumi#12161

sdk: Test case for Provider propagation

---

CHANGELOG_PENDING.md
sdk/Pulumi.Tests/Deployment/DeploymentRunnerTests.cs
sdk/Pulumi/Deployment/Deployment.Runner.cs

Slightly nicer error message when is called `Deployment.RunAsync<TStack>` where `TStack`'s constructor throws.
Let's say you have this stack:
```csharp
using Pulumi;
using System;
internal class ThrowStack : Stack
{
public ThrowStack()
{
throw new Exception("turtles");
}
}
```
And your main method tries to use it:
```csharp
await Deployment.RunAsync<ThrowStack>();
```
When run with `pulumi up`, the actual error is burried in the center of the call stack, obscured by the `TargetInvocationException`:
```
C:\src\MastodonPulumi>pulumi up
Previewing update (dev)
View Live: https://app.pulumi.com/AustinWise/MastodonPulumi/dev/previews/89b8b54a-ff04-479a-a08a-709fe8fb72f4
Type                 Name                Plan     Info
pulumi:pulumi:Stack  MastodonPulumi-dev           2 errors …
```

When instantiating Stack objects, do not wrap exceptions.

---

.github/workflows/pr.yml
.github/workflows/release-sdk.yml

These were warning about still being Node.js 12 actions which are deprecated.

Update setup-dotnet and checkout

---

.github/dependabot.yml

Sets up dependabot to automatically create PRs
to update versions of GitHub Actions used by the repository.
Refs #113

dependabot: Auto-update actions

---

CHANGELOG_PENDING.md
proto/pulumi/codegen/mapper.proto
proto/pulumi/converter.proto
sdk/Pulumi/Deployment/Deployment_Call.cs
sdk/Pulumi/Deployment/Deployment_Invoke.cs
sdk/Pulumi/Provider/PropertyValue.cs
sdk/Pulumi/Provider/Provider.cs

Also fix the PropertyValue.Marshal/Unmarshal names to match the Go SDK. Marshal is to go from PropertyValue to Protobuf, but this SDK was using Unmarshal for that operation.

Sync proto files

---

CHANGELOG_PENDING.md
proto/pulumi/codegen/hcl.proto
proto/pulumi/codegen/loader.proto
proto/pulumi/codegen/mapper.proto
proto/pulumi/converter.proto
proto/pulumi/language.proto
proto/pulumi/provider.proto
proto/pulumi/resource.proto
proto/pulumi/source.proto
sdk/Pulumi/Codegen/Diagnostic.cs
sdk/Pulumi/Converter/Converter.cs
sdk/Pulumi/Pulumi.csproj
sdk/Pulumi/Pulumi.xml

This PR implements a `Converter` abstraction under the `Pulumi.Experimental.Converter` namespace which allows easily building and serving converter plugins from dotnet.
Minimal example:
```cs
using Pulumi.Experimental.Converter;
var converter = Converter.CreateSimple(request =>
{
return ConvertProgramResponse.Empty;
});
await Converter.Serve(converter);
```
In F#:
```fs
open Pulumi.Experimental.Converter
let converter = Converter.CreateSimple (fun request -> ConvertProgramResponse.Empty)
converter
|> Converter.Serve
|> Async.AwaitTask
|> Async.RunSynchronously
```
Here, you give the converter implementation to `Converter.CreateSimple`, this gives you an instance of `SimpleProgramConverter` which implements `Converter`. Then you use that instance as an argument for `Converter.Serve` …

[sdk] Implement Converter abstraction for building converter plugins

---

sdk/Pulumi.Automation.Tests/EventLogWatcherTests.cs
sdk/Pulumi.Automation.Tests/Serialization/GeneralJsonConverterTests.cs
sdk/Pulumi.Automation/Events/EventLogWatcher.cs
sdk/Pulumi.Automation/Serialization/LocalSerializer.cs

Adds some guards in a non-destructive way against invalid event data.
Will hopefully resolve: https://github.com/pulumi/pulumi-dotnet/issues/166

Defend against invalid event data being parsed as json

---

.github/workflows/pr.yml
.gitignore
build/Program.fs
codecov.yml
sdk/Pulumi.Automation.Tests/Pulumi.Automation.Tests.csproj
sdk/Pulumi.Tests/Pulumi.Tests.csproj

This adds unit test coverage of the SDK and uploads to codecov. Will follow-up with lang host coverage in a separate PR.
Part of #162

ci: Add coverage tracking

---

CHANGELOG_PENDING.md
sdk/Pulumi.Tests/Deployment/DeploymentRunnerTests.cs
sdk/Pulumi/Core/Output.cs
sdk/Pulumi/Serialization/Serializer.cs

Fixes #139 
When using an `async` lambda inside `Apply` where we `await` asynchronous functions that don't return anything, the lambda gets the signature `Func<T, Task>`. Giving that to `Apply` the returned `Task` is not awaited because the overload chosen for the `Apply` is the one accepting `Func<T, U>` and this overload doesn't know how to await and register `U` where `typeof(U) == typeof(Task)`
Because we are not registering the task, it is not awaited properly and the Pulumi program runs to completion before the task is resolved. 
We can easily repro this behavior as follows:
```cs
using System.Threading.Tasks;
using System;
using Pulumi;
await Deployment.RunAsync(() => 
{
Output.Create(0).Apply(async _ => 
{
await LongFailingTask();
});
});
async Task LongFailingTask()
{ …
```

[sdk] Register and await tasks created from `Apply` that don't return anything.

---

sdk/Pulumi/Testing/MockMonitor.cs

This just makes the return value of `SupportsFeature` behave the same as the Node, Python, and Go SDKs, where all features are supported _except_ output values, so that `Output<T>` values don't show up in `MockResourceArgs` inputs.
Reference: https://github.com/pulumi/pulumi/pull/14118

Make MockMonitor return true for all features except outputValues

---

.changes/unreleased/Improvements-200.yaml
sdk/Pulumi.Tests/Resources/ComponentResourceTests.cs
sdk/Pulumi/Resources/ComponentResource.cs
sdk/Pulumi/Testing/IMocks.cs
sdk/Pulumi/Testing/MockMonitor.cs

When writing component resources, at the very end of the constructor logic, developers have to make a call to `RegisterOutputs(...)` and provide a bag of outputs from the instance properties declared with `[Output]` property. 
This PR makes it such that developers can use `RegisterOutputs()` without providing anything and it will use reflection to deduce the keys and values of the outputs from the properties of the component resource. It works as follows:
- ~Any property of type `Output<T>` is considered an output with the key equal to the name of the property~
- Any property marked with attribute `[Output]` is considered an output the key equal to the name of the property
- Any property marked with attribute `[Output(name: "<overriddenPropertyName>")]` is considered an output the key …

[sdk] Implement reflection-based RegisterOutputs for component resources

---

.changes/unreleased/Improvements-201.yaml
sdk/Pulumi.Tests/Provider/PropertyValueTests.cs
sdk/Pulumi/Provider/PropertyValue.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs
sdk/Pulumi/Serialization/Serializer.cs

This PR implements a deserializer from `PropertyValue` into objects via reflection, to be used in native-provider implementations that operate on `PropertyValue` instead of the lower-level `Struct` and `Value` from gRPC. 
The implementation handles most commonly used primitive types and their containers: `string`, `int`, `bool`, `double`, enums, nullable types, arrays, immutable arrays, lists, dictionaries, immutable dictionaries, inputs, input list, input map and nested objects. 
When deserializing an object, if a non-nullable _primitive_ property is missing, an exception is thrown. However, this doesn't include arrays, dictionaries or lists: an empty container is constructed when the data is empty or missing. Also for strings, an empty string is created when deserializing from `Null` or …

[sdk] Initial implementation of a reflection-based PropertyValue deserializer

---

.changes/unreleased/Improvements-210.yaml
sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/Pulumi.Automation.Tests/MoolumiFactAttribute.cs
sdk/Pulumi.Automation/LocalWorkspace.cs
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Automation/Workspace.cs
sdk/Pulumi.Automation/WorkspaceStack.cs
sdk/Pulumi/Pulumi.xml

Adds support for environment add/rm commands to dotnet.

Add environment add and remove commands to automation api

---

.changes/unreleased/Improvements-219.yaml
sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi/Pulumi.csproj

Fixes https://github.com/pulumi/pulumi-dotnet/issues/218.
2.51.0 seems to be the latest release we can safely update to.
2.52 and later of Grpc.Tools doesn't work on old macos versions (https://github.com/grpc/grpc/issues/32558).
2.57 and later Grpc libraries dropped support for netcore3 which we're still building for, although _technically_ it's well out of support so we ought to drop it at some point but we hit lots of pain last time we tried (https://github.com/pulumi/pulumi/issues/11768).

Update Grpc dependencies

---

.github/workflows/release-dotnet-provider.yml

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

ci: Use GITHUB_OUTPUT envvar instead of set-output command

---

.github/workflows/pr.yml

Currently we only run a [certain integration tests](https://github.com/pulumi/pulumi-dotnet/blob/a5f3d6cefbab84efacd4df74a21aac8d3f3b3d2f/.github/workflows/pr.yml#L67) on windows & Mac.
Allow running the sdk and automation tests on windows & Mac by setting the `ci/test` label.

Run build & test steps on windows & macos if the ci/test label is set

---

.changes/unreleased/Improvements-235.yaml
sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi.Automation/Serialization/LocalSerializer.cs
sdk/Pulumi.FSharp/Pulumi.FSharp.fsproj
sdk/Pulumi/Core/Output.cs
sdk/Pulumi/Deployment/GrpcEngine.cs
sdk/Pulumi/Deployment/GrpcMonitor.cs
sdk/Pulumi/Provider/Host.cs
sdk/Pulumi/Pulumi.csproj

netcore 3.1 is well out of it's support lifecycle. The code generators in pulumi/pulumi no longer emit any reference to netcoreapp3.1. Users should have updated to net6.0 or later, as netcoreapp3.1 is no longer supported by Microsoft either.

Remove netcoreapp3.1 support

---

.changes/unreleased/Improvements-231.yaml
CONTRIBUTING.md
sdk/Pulumi.Tests/Serialization/ConstructorParamAttributeTests.cs
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Serialization/Attributes.cs
sdk/Pulumi/Serialization/Converter.cs

This PR is in support of https://github.com/pulumi/pulumi/issues/14130.
I have a local override for the native provider in question to use the changes in this PR, as well as codegen changes in pulumi/pulumi using the PR https://github.com/pulumi/pulumi/pull/14246 with additional changes to emit the attribute introduced in this PR.
Here's how it looks in practice in a provider's SDK:
```csharp
[OutputType]
public sealed class ListOneClicksProperties
{
public readonly ImmutableArray<Outputs.OneClicks> _1Clicks;
[OutputConstructor]
private ListOneClicksProperties([OutputConstructorParameterAttribute("1_clicks")] ImmutableArray<Outputs.OneClicks> _1Clicks)
{
this._1Clicks = _1Clicks;
}
}
```

Add attribute to handle deserialization of constructor parameters with name overrides

---

.changes/unreleased/Improvements-234.yaml
.github/workflows/pr.yml
integration_tests/transformations_remote/.gitignore
integration_tests/transformations_remote/Program.cs
integration_tests/transformations_remote/Pulumi.yaml
integration_tests/transformations_remote/Random.cs
integration_tests/transformations_remote/Transformations.csproj
integration_tests/transformations_simple/Program.cs
integration_tests/transformations_simple_test.go
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Tests/Resources/CustomTimeoutsTests.cs
sdk/Pulumi/Core/Alias.cs
sdk/Pulumi/Deployment/Callbacks.cs
sdk/Pulumi/Deployment/Deployment.cs
sdk/Pulumi/Deployment/Deployment_Prepare.cs
sdk/Pulumi/Deployment/Deployment_RegisterResource.cs
sdk/Pulumi/Deployment/Deployment_Serialization.cs
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Resources/CustomTimeouts.cs
sdk/Pulumi/Resources/ResourceOptions.cs
sdk/Pulumi/Resources/ResourceOptions_Copy.cs
sdk/Pulumi/Resources/ResourceTransform.cs
sdk/Pulumi/Resources/StackOptions.cs
sdk/Pulumi/Serialization/Serializer.cs
sdk/Pulumi/Stack.cs
sdk/Pulumi/Testing/MockMonitor.cs

This adds a new experimental feature to the dotnet SDK to register remote transform functions. These are currently all prefixed 'X' to show they're experimental.
These transform functions will run even for resources created inside MLCs.

Support for remote transforms

---

integration_tests/integration_dotnet_smoke_test.go

Clearly somethings changed in the CLI recently but because of https://github.com/pulumi/pulumi/issues/14765 it wasn't caught. 
We need to fix this in pu/pu re-enable those tests, then fix up this test in pu-dotnet.

Skip stack reference test, till the core ones can be renabled

---

.changes/unreleased/Improvements-251.yaml
sdk/Pulumi.Tests/StackTests.cs
sdk/Pulumi/Stack.cs

I want to be able to write a base class for a stack, which will be reused for a few projects which have separate, but similar infrastructures. Currently, the Output properties defined on the base class are not being registered in the derived stacks because of the `BindingFlags.DeclaredOnly` flag used in the `Stack.RegisterPropertyOutputs` method.
In this PR I remove this flag. Instead, I explicitly cut off properties from ancestors of the `Stack` class (currently the `Resource` class has `Urn` output property and I believe this was the reason to add the `DeclaredOnly` flag in the first place).
Check the test I added to see exactly what I wanted to achieve.

Handle Outputs in derived Stacks

---

.changes/unreleased/Improvements-250.yaml
sdk/Pulumi.FSharp/Library.fs

Since F# 6 improvements to implicit type conversions, it has been much more enjoyable to work with Pulumi.
Though I find there are still a few situations where it's not as easy as it could be, for me they were often properties with `InputList` type.
Adding these to the Ops module would make life easier.

Add more FSharp Ops helpers

---

.changes/unreleased/Improvements-258.yaml
sdk/Pulumi.Tests/Core/OutputTests.cs
sdk/Pulumi/Core/Output.cs

Similar to the changes we recently made for the Go, Node and Python SDKs, Dotnet should also support unknowns during `pulumi up`. Implement that.

allow unknown values during up for apply

---

.changes/unreleased/Bug Fixes-263.yaml
sdk/Pulumi/Pulumi.csproj

Fixes https://github.com/pulumi/pulumi-dotnet/issues/249.
We should get conformance tests up and running to confirm large request/responses to and from the engine work ok. For now we can just pin as the old version seemed to work.hw

Pin Google.Protobuf to 3.24

---

.changes/unreleased/Improvements-259.yaml
proto/pulumi/callback.proto
proto/pulumi/codegen/loader.proto
proto/pulumi/codegen/mapper.proto
proto/pulumi/converter.proto
proto/pulumi/language.proto
proto/pulumi/provider.proto
proto/pulumi/resource.proto
proto/pulumi/testing/language.proto
sdk/Pulumi/Deployment/Deployment_ReadOrRegisterResource.cs
sdk/Pulumi/Deployment/Deployment_ReadResource.cs
sdk/Pulumi/Deployment/Deployment_RegisterResource.cs

Similar to what we're doing to the other SDKs in https://github.com/pulumi/pulumi/pull/15740, this enables dealing with the Result field in the RegisterResource response.

Make dotnet SDK support result reporting

---

.changes/unreleased/Improvements-265.yaml
sdk/Pulumi.Automation/DestroyOptions.cs
sdk/Pulumi.Automation/UpOptions.cs
sdk/Pulumi.Automation/WorkspaceStack.cs

Similar to what we did for Go, Python and NodeJS, add ContinueOnError to the dotnet automation api.

add ContinueOnError to Automation API

---

.changes/unreleased/Bug Fixes-266.yaml
sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi/Pulumi.csproj

This reverts commit d87f6a0f9d4780ed27bea8f97a7bff6a73a27914.
Fixes https://github.com/pulumi/pulumi-dotnet/issues/249.

Revert "Update Grpc dependencies (#219)"

---

README.md

This is useful during development, but seems undocumented so far.

document the command to format the SDK

---

.changes/unreleased/Bug Fixes-279.yaml
.changes/unreleased/Improvements-270.yaml
.changes/unreleased/Improvements-277.yaml
.changes/v3.64.0.md

Merging this should kick off the merge workflow according to https://github.com/pulumi/pulumi-dotnet/blob/main/CONTRIBUTING.md#release

release pulumi dotnet 3.64.0

---

.changes/unreleased/Improvements-256.yaml
.github/workflows/pr.yml
sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi/Pulumi.csproj

Fixes https://github.com/pulumi/pulumi-dotnet/issues/218.
MacOS runner version had to be bumped to 12 because of https://github.com/grpc/grpc/issues/32558

Update Grpc dependency

---

.github/workflows/pr.yml

It's easy to forget to check in the xml doc files that are created during the build.  See for example https://github.com/pulumi/pulumi-dotnet/pull/299.
Add a CI check that checks if the workspace is clean, to make sure all the relevant files have been checked in.

check if the workspace is clean after building the SDKs

---

.changes/unreleased/Bug Fixes-298.yaml
integration_tests/transformations_remote/Program.cs
integration_tests/transformations_simple_test.go
sdk/Pulumi.Tests/Serialization/OutputValueTests.cs
sdk/Pulumi/Deployment/Deployment_Prepare.cs
sdk/Pulumi/Serialization/Deserializer.cs

This change adds support for deserializing output values and ensures they work for transforms. This is necessary as the engine will send output values to transforms, so we need to handle deserializing them before calling the transform and then properly serializing them when returning the results.
Fixes #297

Add support for deserializing output values

---

.github/workflows/pr.yml

Our tests seem to pollute the workspace at least for community PRs. The intention of adding the workspace clean script was never to catch that, but rather just that all the generated files are committed correctly.
Move the check up to make sure to check just that.

check for workspace clean after the build not after tests

---

.changes/unreleased/Bug Fixes-301.yaml
sdk/Pulumi.FSharp/Library.fs

Fixing my previous PR #250.
Without these annotations type inference incorrectly determines the other type as `<obj>`.

fix: Add type annotations for proper inference

---

.changes/unreleased/Bug Fixes-304.yaml
sdk/Pulumi/Deployment/GrpcMonitor.cs

While creating integration tests I faced a race condition in GrpcMonitor when the channel retrieved from the static _monitorChannels was null although the key had already been set.
Replacing the complex implementation with custom locking by the standard pattern ConcurrentDictionary<K, Lazy<V>> has resolved this.

Fix race condition in GrpcMonitor's GrpcChannel management

---

.changes/unreleased/Improvements-296.yaml
sdk/Pulumi.Automation.Tests/Data/import/Pulumi.yaml
sdk/Pulumi.Automation.Tests/Data/import/expected_generated_code.yaml
sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/Pulumi.Automation/ImportOptions.cs
sdk/Pulumi.Automation/ImportResource.cs
sdk/Pulumi.Automation/ImportResult.cs
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Automation/Serialization/LocalSerializer.cs
sdk/Pulumi.Automation/Serialization/UpdateKindConverter.cs
sdk/Pulumi.Automation/UpdateKind.cs
sdk/Pulumi.Automation/WorkspaceStack.cs

Addressing https://github.com/pulumi/pulumi/issues/8237
Following a similar pattern to how I implemented the NodeJS API https://github.com/pulumi/pulumi/pull/16615
This PR extends the automation API to allow batch importing resources into a stack. An example of how this looks like:
```cs
var result = await stack.ImportAsync(new()
{
Protect = false,
Resources = new()
{
new()
{
Type = "random:index/randomPassword:RandomPassword",
Name = "randomPassword",
Id = "supersecret"
}
}
});
```
Also implements an enum converter for `UpdateKind` since JSON deserialization was failing when encountering update kind `resource-import`, this is now fixed.

[automation] Implement Stack.ImportAsync() for batch importing resources into a stack

---

.changes/unreleased/Bug Fixes-306.yaml
sdk/Pulumi.Tests/Provider/PropertyValueTests.cs
sdk/Pulumi/Provider/PropertyValue.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs

Fix extracted from https://github.com/pulumi/pulumi-dotnet/pull/275
I also found the same bug for unkown secrets inputs. Which is also fixed.
I did not copy the intgeration test over since that was done using a c# component provider
But it is present in  the other pr, I added some unit tests to cover these edge cases though.

Fix unknown inputs deserialization

---

.changes/unreleased/Bug Fixes-307.yaml
.github/workflows/pr.yml
integration_tests/failing_transformation_exits/Program.cs
integration_tests/failing_transformation_exits/Pulumi.yaml
integration_tests/failing_transformation_exits/failing_transformation_exits.csproj
integration_tests/integration_dotnet_test.go
sdk/Pulumi/Deployment/Deployment.EnginerLogger.cs

Fixes #291 Fixes #174 (duplicate of the former)
The problem is that the task that is created for logging the exception never resolves. Simplified to use `Task.Run(...)` without `Task.ContinueWith(...)` and added an integration test to verify that a failing transformation actually exits the program without hanging.

Fix program hanging when a resource transformation throws an exception

---

.changes/unreleased/Bug Fixes-308.yaml
sdk/Pulumi.Tests/Provider/PropertyValueTests.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs

Fixes https://github.com/pulumi/pulumi-dotnet/issues/308
I also limited the properties that are tried to be deserialized to not include non instance fields.
The generated args classes all have a static Empty Property that threw an error otherwise.

Fix handling of input properties with backing fields

---

.changes/unreleased/Improvements-311.yaml
sdk/Pulumi.Tests/Core/OutputTests.cs
sdk/Pulumi.Tests/StackTests.cs
sdk/Pulumi/Deployment/DeploymentInstance.cs
sdk/Pulumi/Deployment/Deployment_Call.cs
sdk/Pulumi/Deployment/Deployment_Invoke.cs
sdk/Pulumi/Deployment/Deployment_Prepare.cs
sdk/Pulumi/Deployment/Deployment_ReadOrRegisterResource.cs
sdk/Pulumi/Deployment/Deployment_ReadResource.cs
sdk/Pulumi/Deployment/Deployment_RegisterResource.cs
sdk/Pulumi/Deployment/GrpcMonitor.cs
sdk/Pulumi/Deployment/IDeployment.cs
sdk/Pulumi/Deployment/IDeploymentInternal.cs
sdk/Pulumi/Deployment/IMonitor.cs
sdk/Pulumi/Deployment/InvokeOptions.cs
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Resources/CustomResource.cs
sdk/Pulumi/Resources/ProviderResource.cs
sdk/Pulumi/Resources/RegisterPackageRequest.cs
sdk/Pulumi/Resources/Resource.cs
sdk/Pulumi/Testing/MockMonitor.cs

This PR extends the SDK to support parameterized providers, accepting a `RegisterPackageRequest` in `Read`, `RegisterResource`, `Call` and `Invoke` such that we can (lazily) register a parameterized package, retrieve its reference from the engine and use it in the request of these operations.
Addresses https://github.com/pulumi/pulumi/issues/16798

[sdk] Support package parameterization for Read/RegisterResource/Call/Invoke

---

CONTRIBUTING.md

If this is not bumped, codegen tests eventually start failing once providers start requiring the newer version.

add a note about bumping the version in pulumi/pulumi

---

.changes/unreleased/Bug Fixes-318.yaml
sdk/Pulumi.Tests/Resources/ComponentResourceTests.cs
sdk/Pulumi/Deployment/DeploymentInstance.cs
sdk/Pulumi/Deployment/Deployment_Call.cs
sdk/Pulumi/Deployment/Deployment_Invoke.cs
sdk/Pulumi/Deployment/IDeployment.cs
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Resources/ProviderResource.cs

Fixes #317 
In #311 I introduced a new optional parameter for the constructor of `ProviderResource` so previously it was:
```cs
public ProviderResource(
string package,
string name,
ResourceArgs args,
CustomResourceOptions? options = null)
```
and it became:
```cs
public ProviderResource(
string package,
string name,
ResourceArgs args,
CustomResourceOptions? options = null,
RegisterPackageRequest? registerPackageRequest = null)
```
Since the parameter is optional, I assumed that it is not a breaking change. However, when using provider SDKs built with an older version Pulumi (before v3.66.0) in combination with this new version (v3.66.0) it gives a _runtime_ error:
```
System.MissingMethodException: Method not found: 'Void Pulumi.ProviderResource..ctor(System.String, System.String, …
```

Fix binary compatibility with provider SDKs built using older version of the core SDK

---

sdk/Pulumi.Automation.Tests/EventLogWatcherTests.cs

We want to make sure unknown events from the engine (e.g. events that are newly added) don't break the use of the automation API in dotnet.  Add a test to verify just that.

add a test showing that unknown events are handled

---

Makefile
README.md

Add a simple makefile to build and install the language runtime for dotnet.  We have a homegrown build system in this repo, but that doesn't even return the errors for failed Go builds.  Rather than trying to fix that, it's better to try and converge the build systems for all our projects, as all others are using Make.
The `dotnet run` commands will keep working for those that prefer them.

add Makefile to build the language runtime

---

sdk/Pulumi/Provider/Provider.cs

Noticed while reviewing https://github.com/pulumi/pulumi-dotnet/pull/275. We called this helper `Marshal` but it's actually `Unmarshalling` a PropertyValue from it's wire encoding.

Rename Marshal helper to Unmarshal

---

.changes/unreleased/Bug Fixes-337.yaml
sdk/Pulumi.Tests/Provider/PropertyValueTests.cs
sdk/Pulumi/Core/OutputUtilities.cs
sdk/Pulumi/Provider/PropertyValue.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs
sdk/Pulumi/Pulumi.xml

Prompted by reviewing https://github.com/pulumi/pulumi-dotnet/pull/335, found a number of issues in the serialisation of output values.
This also fixes one of the issues fixed in https://github.com/pulumi/pulumi-dotnet/pull/335 where `IInput` values weren't serialised correctly.
To help support testing this I've added a new helper to `OutputUtilities` to add a dependency to an output. Similar to `OutputUtilities.CreateUnknown` this isn't expected to be used in normal programs, but its useful for tests.

Fix output serialisation in the provider library

---

.changes/unreleased/Bug Fixes-343.yaml
pulumi-language-dotnet/main.go
sdk/Pulumi/Deployment/Deployment_Run.cs

Two fixes for debugger support:
1. Fix unintentional shadowing of the `binaryPath` variable in the langhost's `Run` method. It's currently being shadowed, which means we won't run `dotnet <name>.dll` needed to be able to attach a debugger. (This "regressed" when addressing PR feedback in #332).
2. Fix where we're waiting for the debugger to be attached in the SDK. Right now, we're only waiting in a single overload of `Deployment.RunAsync`. If your Pulumi program is calling another overload, it won't wait for the debugger to attach. This change moves the logic to a centralized place that all `RunAsync` overloads call through to. It also converts the logic back into be async by awaiting `Task.Delay` with a one second delay, since it can now be async in this new location.
Fixes #344

Fix debugger support

---

.changes/unreleased/Improvements-347.yaml
sdk/Pulumi/Deployment/Deployment.cs
sdk/Pulumi/Deployment/Deployment_Prepare.cs

Adds the required bit to check for the parameterisation flag.
We'll also want to do a 3.68 release with this as soon as possible to match the sdk-gen changes that have gone into pulumi: https://github.com/pulumi/pulumi/pull/17153/files#diff-c44352515fd31f42be144a763ab5771fe41195a15c2c1213d41a8cbc94dd69d4R2318

Add parameterisation feature flag

---

.changes/unreleased/Improvements-350.yaml
sdk/Pulumi.Automation/OperationType.cs
sdk/Pulumi.Automation/PublicAPI.Shipped.txt
sdk/Pulumi.Automation/Serialization/OperationTypeConverter.cs

Lessen the strictness of `OperationTypeConverter` to allow unknown operations. This is a postmortem follow-up after we added a new operation (`"output-changes"`) in the engine that the .NET Automation API couldn't handle, resulting in an `InvalidOperationException` being thrown. Now, when an unknown operation is encountered, `OperationType.Unknown` will be returned rather than throwing.
Fixes #292

Allow unknown operations in OperationTypeConverter

---

.changes/unreleased/Improvements-354.yaml
sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi.Automation/Serialization/Yaml/ProjectRuntimeOptionsYamlConverter.cs
sdk/Pulumi.Automation/Serialization/Yaml/ProjectRuntimeYamlConverter.cs
sdk/Pulumi.Automation/Serialization/Yaml/StackSettingsConfigValueYamlConverter.cs

Fixes #353
YamlDotNet added new parameters to the `IYamlTypeConverter` methods in [v16.0](https://github.com/aaubry/YamlDotNet/releases/tag/v16.0.0).
This PR updates the `YamlDotNet` package to latest version (v16.1.2) and adapts custom converters to this breaking change.

Updating YamlDotNet to latest version

---

.changes/unreleased/Bug Fixes-355.yaml
.changie.yaml
pulumi-language-dotnet/main.go
pulumi-language-dotnet/main_test.go

When attaching a debugger, we first need to build the binary, and then run it, because the debugger doesn't work properly when just using `dotnet run`.  This currently has two bugs:
1) it doesn't respect the entry point the user specifies in the Pulumi.yaml 
2) it only detects .csproj projects, not .fsproj or .vbproj projects,
so it doesn't work out of the box for F# or VB projects.  This is
made worse by the bug above, since the user has no workaround for
it.
This PR fixes both of those issues, by respecting the entry point if it is given, and if it is not, by also looking at project files with a .fsproj or .vbproj extension.
Fixes https://github.com/pulumi/pulumi-dotnet/issues/352

improve the detection of project files when in debug mode

---

sdk/Pulumi/Provider/Provider.cs

We consistently want to refer to Component Providers, which is the official name, and not MLCs.  Do so here.

refer correctly to component providers

---

.github/workflows/pr.yml
Makefile

Currently the CI workflow in this repo runs each integration test individually.  This makes it very easy to forget to add a test to the list, that's then never run in CI, even though it should be.
Fix this by introducing a new Makefile target, to run all integration tests, and running that in CI instead of spelling each test out individually, which is very brittle.

always run all integration tests

---

build/Publish.fs
sdk/Directory.Build.props

Resolves #351 
The error message in the issue suggests that `dotnet build` isn't creating the nuget package even though we have a property `GeneratePackageOnBuild` set in the project settings. 
~~This PR fixes the problem by explicitly executing `dotnet pack` against the projects before trying to find the nuget package and publishing it~~
EDIT: removed `TargetFramework` property from directory build props

[ci/publishing] Fix generating nuget packages on build for dev releases

---

.changes/unreleased/Improvements-364.yaml
sdk/Pulumi/Exceptions/RunException.cs

As per discussion in #203 . This is a simple improvement in order to make the exception assertable by testing frameworks such as `FluentAssertions` using:
```csharp
var action = () => 
{
// (...) // provision failing pulumi resources here
};
action.Should().Throw<Pulumi.RunException>();
```
This will significantly improve testing scenarios where exceptions are being thrown, as everything gets wrapped in an internal `Pulumi.RunException` while testing:
```csharp
// Disassembled code
internal static async Task<(ImmutableArray<Resource> Resources, Exception? Exception)> TryTestAsync(
IMocks mocks, Func<IRunner, Task<int>> runAsync, TestOptions? options = null)
{
var engine = new MockEngine();
var monitor = new MockMonitor(mocks);
await CreateRunnerAndRunAsync(() => new Deployment(engine, …
```

feat(#203): RunException access modifier set to public. Docs updated

---

.changes/unreleased/bug-fixes-368.yaml
sdk/Pulumi.Tests/Core/OutputTests.cs
sdk/Pulumi/Core/Output.cs

Our `OutputJsonConverter` fails to account for `InputList<T>`, so any input lists nested in a serialized data structure causes serialization to fail. Reported by a customer trying to serialize Azure Native dashboard data types.
The fix expands `OutputJsonConverter` to support `InputList<T>`. It piggybacks on the existing `InputJsonConverterInner` implementation by passing an `ImmurableArray<T>` generic argument to it.
Fixes https://github.com/pulumi/pulumi-dotnet/issues/367

Support input lists in JsonSerializer.SerializeAsync

---

.changes/unreleased/bug-fixes-368.yaml
sdk/Pulumi.Tests/Core/OutputTests.cs
sdk/Pulumi/Core/Output.cs

#368 fixed `OutputJsonConverter` for `InputList<T>` but it still fails for `InputMap<T>`, so any input maps nested in a serialized data structure causes serialization to fail. Reported by a customer trying to serialize Azure Native dashboard data types.
The fix expands `OutputJsonConverter` to support any type that inherits from `Input<T>`, which includes both `InputList` and `InputMap`. It piggybacks on the existing `InputJsonConverterInner` implementation by passing the right generic argument to it.
Fixes https://github.com/pulumi/pulumi-dotnet/issues/367
Generalizes #368

Generalize InputList<> serialization to maps and other Input<> subtypes

---

sdk/Pulumi/Provider/PropertyValue.cs

Note sure why we missed this before, but one of the possible types for a property value is an `OutputReference`, or `Output`.

Add Output to the PropertyValueType's enum

---

.changes/unreleased/Bug Fixes-378.yaml
sdk/Pulumi.Tests/Provider/PropertyValueTests.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs

When deserializing a Secret property value if its inner value was `Unknown` we would return an input value without `isSecret` set because we reused a `unknownOutput` variable from higher up.
This removes that variable and replaces the two use sites with calls to create the output value directly, one without `isSecret` set  and one with it set.

Fix a bug with unknown secret deseralisation

---

.changes/unreleased/Improvements-381.yaml
sdk/Pulumi/Core/Output.cs
sdk/Pulumi/Provider/PropertyValue.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs

This changes the `PropertyValue` field (`Value`) in `OutputReferences` to normalize `Computed` values to `null` as we use that to represent _unknowns_.
As part of this I overhauled the serialisation logic for `Output<T>`/`Input<T>` to better handle nested property values (e.g. a secret in an output, or an output in a secret).

Normalize Computed in OutputReferences to null

---

sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi/Pulumi.csproj
sdk/Pulumi/Pulumi.xml

We normally do Release builds as part of the workflows, and as part of `dotnet run build-sdk` so make sure the docs get updated for those builds.

Update xml docs on Release builds

---

.changes/unreleased/Improvements-383.yaml
sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/Pulumi.Automation/Commands/LocalPulumiCommand.cs
sdk/Pulumi.Automation/Commands/PulumiCommand.cs
sdk/Pulumi.Automation/LocalWorkspace.cs
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Automation/SecretsProviderOptions.cs
sdk/Pulumi.Automation/Workspace.cs
sdk/Pulumi.Automation/WorkspaceStack.cs

fixes #382 to add the command `pulumi stack change-secrets-provider` to the Automation API.
based on the go implementation https://github.com/pulumi/pulumi/pull/14039.

Add `pulumi stack change-secrets-provider` to automation api

---

.changes/unreleased/Bug Fixes-395.yaml
.github/workflows/pr.yml
.github/workflows/release-sdk.yml
Makefile
integration_tests/integration_dotnet_test.go
pulumi-language-dotnet/main.go

Since https://github.com/pulumi/pulumi/pull/17763 the pwd property is the working directory, not the program directory. We need to fix up RunPlugin to use both directories correctly, loading the csproj from the program directory, but then setting the working directory to pwd.
This also updates the CI jobs to always use the latest version of the CLI. We were running into issues because different runners happened to have different CLI versions installed.
For now I've also disabled fail-fast on the integration tests to make re-running them with flaky tests more likely to pass.

Fix RunPlugin and CI jobs

---

.changes/unreleased/Improvements-385.yaml
sdk/Pulumi.Tests/Core/OutputTests.cs
sdk/Pulumi/Core/Output.cs
sdk/Pulumi/Pulumi.xml

Adds `DeferredOutput<T>` that allows the creation of an `Output<T>` that can later be resolved to the final result of a different `Output<T>`.
This can be used to solve partial circular reference problems. For example given two components that create multiple resources and return some results from that, you would normally have to have all the inputs for one component available to call it and then afterwards call the other component. With an `DeferredOutput<T>` you can instead set up a circular reference:
```csharp
var ocs = new DeferredOutput<int>()
var (resultA1, resultA2) = MakeComponentA(ocs.Output);
var resultB = MakeComponentB(resultA1);
ocs.Resolve(resultB);
```
As long as `MakeComponentA` can resolve its A1 result without needing the incoming output resolved then the above will …

DeferredOutput<T> 

---

.changes/unreleased/bug-fixes-393.yaml
Build.fsproj
build/GitSync.fs
build/Nuget.fs
build/Program.fs
build/Publish.fs
build/PulumiSdkVersion.fs
sdk/Pulumi.Automation/Commands/LocalPulumiCommand.cs

Currently when publishing the Pulumi.Automation SDK there is an expected property PulumiSdkVersion which should be set when building the project
This property is set during buildSdk and testPulumiAutomationSdk but not the publishing targets which provide the resulting nuget package.
This means when a consumer references the Automation Api nuget package they have a version that does not have the required property set causing `LocalPulumiCommand.Install` to fail.
Refactored the F# code to ensure the version is set during publish as well
Fixes #392

Fix publishing SDKs to include required attribute for Pulumi.Automation

---

integration_tests/integration_dotnet_test.go
integration_tests/integration_util_test.go

Workaround for https://github.com/dotnet/sdk/issues/44610 In .NET 9.0 `dotnet run` will print progress indicators to the terminal, even though it should not do this when the output is redirected.
To allow the tests to continue passing we check for the expected substrings anywhere in the stdout messages, not just at the start.

Fix stdout tests

---

.changes/unreleased/Improvements-411.yaml
.goreleaser.yml

Strip the symbol table and DWARF debug information from the production
and dev releases. Note that stack traces don't lose any information from this change.
See https://github.com/pulumi/pulumi/pull/17868

Reduce binary size by stripping debug information

---

.changes/unreleased/bug-fixes-388.yaml
sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/Pulumi.Automation/Runtime/LanguageRuntimeService.cs

When using Automation API inline programs with Pulumi CLI v3.132.0 and later, a warning is emitted because the language host for .NET inline programs does not implement the `GetPluginInfo` RPC (from https://github.com/pulumi/pulumi/pull/17216).
This change adds an implementation for `GetPluginInfo`, which avoids the warning. The implementation returns `"1.0.0"` for the version, which matches [Node.js](https://github.com/pulumi/pulumi/blob/7461bddd65033ba6972e8404b711fd02c1bd5c20/sdk/nodejs/automation/server.ts#L140) and [Go](https://github.com/pulumi/pulumi/blob/7461bddd65033ba6972e8404b711fd02c1bd5c20/sdk/go/auto/stack.go#L1596) (though, [Python](https://github.com/pulumi/pulumi/blob/7461bddd65033ba6972e8404b711fd02c1bd5c20/sdk/python/lib/pulumi/automation/_server.py#L127-L128) returns …

Fix warning for Automation API inline programs

---

sdk/Pulumi/Provider/PropertyValue.cs

Small fix that these two special values should have been marked readonly so users don't mutate them.

Make Null and Computed readonly values

---

.changes/unreleased/Improvements-412.yaml
sdk/Pulumi.Tests/Deployment/DeploymentInvokeDependsOnTests.cs
sdk/Pulumi/Deployment/DeploymentInstance.cs
sdk/Pulumi/Deployment/Deployment_Invoke.cs
sdk/Pulumi/Deployment/IDeployment.cs
sdk/Pulumi/Deployment/InvokeOptions.cs
sdk/Pulumi/Pulumi.xml

Provider functions that take inputs as arguments, and return an output (aka output form invokes), now allow specifying a depends_on option. This allows programs to ensure that invokes are executed after things they depend on, similar to the depdends_on resource option.
Fixes https://github.com/pulumi/pulumi/issues/17753

Allow specifying dependencies for output invokes

---

integration_tests/integration_dotnet_test.go

We're still seeing this test fail on macOS and it looks like it may be affecting Windows as well. Temporarily skip it for now.
Going to see if skipping also removes the flakes on Windows.
#403 tracks fixing the test for real / unskipping.
Fixes #419

Temporarily skip flaky TestDebuggerAttachDotnet test

---

pulumi-language-dotnet/testdata/build-dll/.gitignore
pulumi-language-dotnet/testdata/build-dll/Empty.csproj
pulumi-language-dotnet/testdata/build-dll/Program.cs
pulumi-language-dotnet/testdata/build-dll/Pulumi.yaml

This should fix the TestBuildDll test.
We should still make sure this test is acutually running in CI.
Replaces https://github.com/pulumi/pulumi-dotnet/pull/429
/cc @Zaid-Ajaj

add missing build-dll directory

---

.github/workflows/pr.yml
Build.fsproj
integration_tests/testprovider/TestProvider.cs
integration_tests/testprovider/TestProvider.csproj

With the update to Ubuntu 24.04 for the runners, the preinstalled .NET versions have changed. This revealed some issues with how we select the .NET version to use in the matrix tests. The `actions/setup-dotnet` action does install the version we want, but the dotnet command still use the runner’s default version.
We have to create a `global.json` to make it use the desired version.
https://github.com/actions/setup-dotnet?tab=readme-ov-file#matrix-testing

Fix dotnet version

---

.changes/unreleased/bug-fixes-444.yaml
sdk/Pulumi.Tests/Deployment/DeploymentInvokeDependsOnTests.cs
sdk/Pulumi/Deployment/Deployment_Invoke.cs

Besides the explicitly provided resources from the `dependsOn` option, we need to also take into account the resource dependencies from the invoke’s arguments.
https://github.com/pulumi/pulumi/issues/17747

Wait for resources in the input property dependencies

---

.github/workflows/release-sdk.yml

Follow up to https://github.com/pulumi/pulumi-dotnet/pull/445, which fixed CI on the latest ubuntu runners, but missed the release job.

Fix dotnet setup in release job

---

.changes/unreleased/Improvements-437.yaml
integration_tests/integration_dotnet_test.go
integration_tests/integration_util_test.go
integration_tests/testprovider/TestProvider.csproj
pulumi-language-dotnet/main.go

Found this while on my adventures with dotnet plugins. If your plugin project has any warnings it's unusable in shimless mode (i.e. `RunPlugin`) because msbuild would first print the warning then start the plugin and print the port number. This lead to errors like:
```
error:  plugin [E:\VisualStudio\Projects\pulumi\jsonschema\Provider\pulumi-resource-Provider] wrote an invalid port to stdout: could not parse port: strconv.Atoi: parsing "E:\\VisualStudio\\Projects\\pulumi\\jsonschema\\Provider\\Provider.fsproj : warning NU1903: Package 'System.Text.Json' 6.0.2 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4": invalid syntax
```
When running shimless these warnings don't really matter. So this PR rewrites `RunPlugin` to do the build separately, …

Tolerate plugins with warnings

---

.changes/unreleased/Improvements-449.yaml
sdk/Pulumi.Tests/Serialization/MarshalOutputTests.cs
sdk/Pulumi/Core/InputList.cs
sdk/Pulumi/Core/InputMap.cs
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Serialization/Serializer.cs

Fixes https://github.com/pulumi/pulumi-dotnet/issues/22
InputList and InputMap are types used to make it easier to work with lists/maps where both the overall structure or individual elements can be `Input`s.
The current implementation just flattens everything to a top-level input. That is `InputList<T>` is just `Input<ImmutableArray<T>>`. So if you start with a known empty list then add an unknown input element to it you end up with an unknown list structure. This is not ideal for previews (see #22) and doesn't align with the other SDKs where if you add an unknown element to a list the overall list shape is still known and sent to the engine for preview correctly.
This PR fixes the above by keeping track of non-flattened data inside InputMap/List. i.e. the internal shape of …

Don't flatten outputs to top level for InputList and InputMap

---

.changes/unreleased/Improvements-461.yaml
sdk/Pulumi.Tests/Core/OutputTests.cs
sdk/Pulumi/Core/Output.cs

This PR provides an ability that is already present in the Python and JS languages to to disable converting `Output<T>` to a string. 
Currently in the dotnet language this will return a helpful message in the string contents to advise not to do this but does not fail the pulumi program.
This functionality is opted-in by setting the environment variable `PULUMI_ERROR_OUTPUT_STRING` to `true` or `1` to throw an exception.

Add ability to disable ToString on Output<T>

---

sdk/Pulumi/Core/Output.cs

It doesn't really matter, but I noticed while porting to Java in https://github.com/pulumi/pulumi-java/pull/1665 that the implementation could be simplified slightly (no need for the `List<string>`), so I've gone ahead and updated the code here to match the Java implementation.

Minor simplification in Output<T>.ToString

---

.changes/unreleased/bug-fixes-460.yaml
sdk/Pulumi/Deployment/Deployment_Prepare.cs
sdk/Pulumi/Resources/ProviderResource.cs

Fixes https://github.com/pulumi/pulumi-dotnet/issues/455
When marshalling options back to the engine after resource transforms we were incorrectly sending `provider` and `providers` back as just the URNs. They should in fact be "refs" of the form `<urn>::<id>`.

Fix Provider and Providers in transforms

---

.changes/unreleased/bug-fixes-462.yaml
sdk/Pulumi.Tests/Core/InputTests.cs
sdk/Pulumi.Tests/Serialization/MarshalOutputTests.cs
sdk/Pulumi/Core/InputMap.cs
sdk/Pulumi/Pulumi.xml

Fixes https://github.com/pulumi/pulumi-dotnet/issues/458
Before https://github.com/pulumi/pulumi-dotnet/pull/449 it used to be possible to `Add` the same key value pair to `InputMap` multiple times. This because of a feature of the underlying ConcurrentDictionary which will use `EqualityComparer` to see if the key and value being added are the same as what's in the dictionary already and if so just returns the existing dictionary. 
#449 broke this because now all the values of the dictionary are `Input`s which don't have a sensible notion of equality. This adds some extra handling in our Add method to try and maintain this feature.
It _does_ have two oddities:
1. The exception is recorded on the value, not the map overall. This shouldn't be observable because users can only resolve …

Fix adding duplicate key-value pairs to InputMap

---

.changes/unreleased/bug-fixes-459.yaml
sdk/Pulumi.Tests/Core/InputTests.cs
sdk/Pulumi/Core/InputList.cs
sdk/Pulumi/Core/InputMap.cs
sdk/Pulumi/Pulumi.xml

Fixes https://github.com/pulumi/pulumi-dotnet/issues/456
This is a bit of a sad fix but `InputMap` used to tolerate the implicit cast from dictionary being called with null by just passing that null down. If you tried to call Add or enumerate it would NRE, but if it just got assigned to another resource property the serialiser could handle it.
https://github.com/pulumi/pulumi-dotnet/pull/449 broke this because it always tried to enumerate the incoming immutable dictionary to build the new internal nested immutable dictionary. This fixes it to behave as before were null flows through as null.

Handle null runtime values in InputMap/List cast

---

Makefile

It wasn't immediately obvious to me how to produce a changelog, but `make changelog` was the first thing I tried. This PR adds a `make changelog` command to mimic `pulumi/pulumi`.

Add a `make changelog` command for consistency with `pulumi/pulumi`

---

.changes/unreleased/Improvements-502.yaml
sdk/Pulumi/Pulumi.xml
sdk/Pulumi/Resources/ComponentResource.cs

When generating parameterized .NET SDKs, resources that marked `isComponent: true` in the schema do not support parameterization leading to runtime errors that mentioned missing plugins
```
error: Could not automatically download and install resource plugin 'pulumi-resource-<parameterized-package>' at version v0.0.x
```
This PR adds SDK support for parameterized _remote_ component resources. Still required SDK-gen support from pulumi/pulumi to emit the actual `RegisterPackageRequest` in the newly added constructor overload 
Fixes #503

[sdk] Support parameterization for remote component resources

---

.changes/unreleased/Improvements-468.yaml
sdk/Pulumi.Tests/Provider/ComponentAnalyzerTests.cs
sdk/Pulumi/Provider/ComponentAnalyzer.cs
sdk/Pulumi/Provider/Schema.cs
sdk/Pulumi/Pulumi.xml

Implements `ComponentAnalyzer.GenerateSchema` which takes either an assembly or a list of component resources and produces a serializable package schema structure. Infers component resources and their dependent types. Here are the features that this PR implements and tests:
Resolve https://github.com/pulumi/pulumi-dotnet/issues/468 (we'll track missing features in separate issues)

Schema Analyzer to infer component schemas from classes

---

.changes/unreleased/bug-fixes-506.yaml
integration_tests/provider_construct/dotnet/Component.cs
integration_tests/provider_construct/dotnet/Program.cs
integration_tests/provider_construct/testcomponent-dotnet/Component.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs
sdk/Pulumi/Resources/ComponentResource.cs

The InputAttribute and OutputAttribute have an AttributeUseage  with inherit: true.
When using abstract classes and properties, the current implementation does not handle inheritance of the attributes consistently. In some cases, the attributes are checked with inherit: false, in other cases with inherit:true.
I have made the behavior consistent and as expected from the AttributeUseage of InputAttribute and OutputAttribute.

Consistent inheritance behavior for InputAttribute and OutputAttribute

---

.changes/unreleased/Improvements-507.yaml
integration_tests/integration_dotnet_test.go
integration_tests/provider_component_host/Component.cs
integration_tests/provider_component_host/Program.cs
integration_tests/provider_component_host/PulumiPlugin.yaml
integration_tests/provider_component_host/TestProvider.csproj
integration_tests/provider_component_host/example/Pulumi.yaml
sdk/Pulumi.Tests/Provider/ComponentProviderTests.cs
sdk/Pulumi/Provider/ComponentAnalyzer.cs
sdk/Pulumi/Provider/ComponentProvider.cs
sdk/Pulumi/Provider/ComponentProviderHost.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs
sdk/Pulumi/Pulumi.xml

Similar to other language SDKs, this PR implements a high-level component provider host that discovers schemas and constructors of all components in a given assembly or list of types at runtime.
Instantiating a component provider is now as simple as authoring a component and then calling
```csharp
class Program
{
public static Task Main(string []args) => ComponentProviderHost.Serve(args);
}
```
(see the provider_component_host example)
Resolve https://github.com/pulumi/pulumi-dotnet/issues/469

Component provider host for auto-inferred components

---

sdk/Pulumi.Tests/Provider/ComponentAnalyzerTests.cs
sdk/Pulumi/Provider/ComponentAnalyzer.cs

- Add support for mapping `object` type properties to `Any` in component schemas
- Add test cases for both required and optional `object` type properties
- This allows component providers to accept arbitrary data structures through `object` type properties
- Added unit tests verifying both required and optional object properties are correctly mapped to the 'Any' type in schemas
- All unit tests passing

Add support for object type as Any in component schema

---

sdk/Pulumi.Automation/Pulumi.Automation.csproj
sdk/Pulumi.FSharp/Pulumi.FSharp.fsproj
sdk/Pulumi/Pulumi.csproj

_Follow-up to_: https://github.com/pulumi/pulumi-dotnet/pull/500 and https://github.com/pulumi/pulumi/pull/18619
While net6 isn't actually in support anymore, a hard migration to net8 is causing lots of downstream issues. So leave these projects targeting net6 for now, they'll still build fine with net8.

Keep the main projects on net6.0

---

.changes/unreleased/Bug Fixes-515.yaml
.changes/v3.75.2.md

- [runtime] Revert changes to target net8 in provider SDKs [#515](https://github.com/pulumi/pulumi-dotnet/pull/515)

Changelog for v3.75.2

---

.changes/unreleased/Improvements-431.yaml
sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/Pulumi.Automation/DestroyOptions.cs
sdk/Pulumi.Automation/PreviewOptions.cs
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Automation/UpOptions.cs
sdk/Pulumi.Automation/WorkspaceStack.cs

Fixes #327
- Add `--refresh` preview, up and destroy commands
- Add tests to validate behaviour

Add `--refresh` to Automation Api lifecycle commands

---

pulumi-language-dotnet/language_test.go
pulumi-language-dotnet/testdata/sdks/any-type-function-15.0.0/Pulumi.AnyTypeFunction.csproj
pulumi-language-dotnet/testdata/sdks/component-13.3.7/Pulumi.Component.csproj

Update `pulumi` submodule to the v3.153.0 tag. This brings in two new conformance tests.
- `l1-builtin-project-root` support is being added in #466 
- `l2-component-property-deps` is blocked on .NET programgen support for `Call` (and #488)
Somewhat suspicious that a couple generated SDKs changed (I ran the conformance tests with `PULUMI_ACCEPT=true`). Are we not snapshot comparing those?

Update `pulumi` submodule to v3.153.0 tag

---

.changes/unreleased/bug-fixes-536.yaml
sdk/Pulumi.Tests/Provider/ProviderTests.cs
sdk/Pulumi/Provider/Provider.cs

Passing a --logflow argument to the CLI will make it pass all its arguments to providers. This PR ports this [Node.js implementation](https://github.com/pulumi/pulumi/blob/05970ff66567eeed7723d7b6ee2c37d3b464f580/sdk/nodejs/provider/internals.ts#L30-L53) and [Java implementation](https://github.com/pulumi/pulumi-java/pull/1708) that discards known logging parameters from engine address calculation.
~This change now requires an address while previously it was optional. I believe this is a correct change, again in line with other SDKs, but let me know if there are legit cases when address is not passed.~

Handle logging arguments in provider's getEngineAddress

---

.changes/unreleased/Improvements-555.yaml
sdk/Pulumi.Tests/Provider/ComponentAnalyzerTests.cs
sdk/Pulumi.Tests/Provider/ComponentProviderHostTests.cs
sdk/Pulumi.Tests/Provider/ComponentProviderTests.cs
sdk/Pulumi/Provider/ComponentAnalyzer.cs
sdk/Pulumi/Provider/ComponentProvider.cs
sdk/Pulumi/Provider/ComponentProviderHost.cs
sdk/Pulumi/Provider/Schema.cs
sdk/Pulumi/Pulumi.csproj
sdk/Pulumi/Pulumi.xml

Key changes around the ComponentProviderHost:
- Introduces a new property `Namespace` to package metadata
- For assembly name `Foo.Bar.Buzz` or `Foo.Buzz` calculated package name as `buzz` and namespace as `foo`, for assembly name `Buzz` leaves namespace empty
- Namespace and package names are kebab-cased with Humanizer
- Changes the ComponentProvider constructor to accept the entire `metadata` record, which is built in the host
- ComponentProviderHost is the still "simple mode" entry point with sensible defaults, users can eject to ComponentProvider pretty easily

Infer namespaces in dotnet

---

.changes/unreleased/Improvements-556.yaml
sdk/Pulumi/Provider/ComponentProviderHost.cs

Default the component provider schema version to "0.0.0" if not provided for now, otherwise SDK codegen gets confused without a version.

Default the component provider version to 0.0.0

---

.editorconfig
sdk/Pulumi/Provider/ComponentAnalyzer.cs
sdk/Pulumi/Provider/Provider.cs

This change specifies a StringComparison in calls to `StartsWith` and `EndsWith`, and enables the [analyzer rule](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1310) to enforce it going forward.
Note: We should enable a more aggressive set of analysis rules beyond the default set (likely via `<AnalysisMode>Recommended</AnalysisMode>` in the .csproj files), but that requires more fixes, so just enabling this specific rule for now.

Specify StringComparison for correctness

---

.changes/unreleased/Improvements-554.yaml
sdk/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/Pulumi.Automation/DestroyOptions.cs
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Automation/WorkspaceStack.cs

Part of https://github.com/pulumi/pulumi/issues/18725. This PR adds the ability to run destroy --preview-only via the .NET automation API.

Add the `--preview-only` option for `destroy` in the .NET API

---

.changes/unreleased/Bug Fixes-561.yaml
integration_tests/transformations_remote/Program.cs
sdk/Pulumi/Deployment/Callbacks.cs
sdk/Pulumi/Deployment/Deployment.cs

The `Callback` system is what allows the engine to callback to the language runtime to invoke generic code. Currently just used for the transforms system, but soon to be extended for other uses as well.
We were incorrectly not propagating the async context from where the callback system was created (somewhere inside the users program as part of resource registration call) to the threads that the callbacks run on (in the kestral server threadpool).
This meant that inside a transform function you couldn't access any of the async context that you had access to just outside the transform function. Importantly this includes the deployment instance that allows access to the engine.
We probably wouldn't recommend registering more resources from the transform function (although, you _could_) but …

Capture async context for engine callback methods

---

.changes/unreleased/Improvements-562.yaml
sdk/Pulumi/Provider/PropertyValue.cs

Noticed this while working on the python SDK. Rather than having this function return a partial result we can _always_ return a `PropertyValue` by just translating `OutputReferences` that have a null value to `Computed` values (which is what the null inner value really means).

Change PropertyValue.TryUnwrap to Unwrap

---

integration_tests/testprovider/TestProvider.cs

When we changed the test provider to test parameterised schemas we accidentally made it always parameterised. This changes it so that it won't always have a "parameterisation" block, and adds the necessary "supportPack" flag to keep existing tests working with local sdks.

Don't always return a parameterised schema

---

.changes/unreleased/Bug Fixes-570.yaml
sdk/Pulumi.Tests/Provider/PropertyValueTests.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs

Error was raised to me on community slack.
This fixes deserializing into an `InputMap<T>` when one of the values is an unknown or computed value. Before this fix it would error that, for example, `string` was expected not `Output<T>`.

Fix deserialisation of InputMaps with nested output values

---

README.md

This has been removed in 9b585c8fe0f42f86f07075449e5227260c14af10, remove it from the README as well to avoid confusion.

remove the mention of sync-proto-files from README

---

.changes/unreleased/Improvements-573.yaml
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Automation/UpdateOptions.cs
sdk/Pulumi.Automation/WorkspaceStack.cs

Add ConfigFile property to UpdateOptions class, which is inherited by all
operation options (UpOptions, PreviewOptions, RefreshOptions, DestroyOptions).
This enables specifying a YAML file containing stack configuration values
when performing operations through the .NET Automation API.
This will fix part of https://github.com/pulumi/pulumi/issues/17773

feat(automation): add config-file option to operation options

---

pulumi-language-dotnet/go.mod
pulumi-language-dotnet/go.sum

Similar to https://github.com/pulumi/pulumi/pull/17410, pulumi-dotnet also uses the atotto/clipboard library, which can sometimes fail when loading DLLs.  Replace this with a version that lazy loads the DLLs, which solves to avoid the panic when loading the library.
Part of https://github.com/pulumi/pulumi/issues/19185

replace atotto/clipboard with version that lazy loads DLLs

---

.changes/unreleased/Bug Fixes-570.yaml
.changes/unreleased/Improvements-573.yaml
.changes/v3.79.0.md
.github/workflows/pr.yml

Also adding a lint step to check changelog entries added are valid. The `.changes/unreleased/Bug Fixes-570.yaml` file had "Bug Fixes" instead of "bug-fixes" for it's kind that I had to fix before `changie batch auto` would run.

Changelog for 3.79 release

---

.changes/unreleased/Improvements-582.yaml
sdk/Pulumi.Automation/DestroyOptions.cs
sdk/Pulumi.Automation/PreviewOptions.cs
sdk/Pulumi.Automation/UpOptions.cs
sdk/Pulumi.Automation/UpdateOptions.cs
sdk/Pulumi.Automation/WorkspaceStack.cs

The final PR in this saga. This PR adds the `--exclude` and `--exclude-dependents` to the Automation API.
* https://github.com/pulumi/pulumi-java/pull/1781
* https://github.com/pulumi/pulumi/pull/19333
* https://github.com/pulumi/pulumi/pull/19310
* https://github.com/pulumi/pulumi/pull/19270

Add `--exclude` and `--exclude-dependents` to the Automation API

---

.github/workflows/on-release.yml
.github/workflows/pr.yml
.github/workflows/release-dotnet-provider.yml
.github/workflows/release-sdk.yml

These changes migrate this repo's GitHub Actions Workflows to use ESC secrets instead of GitHub Secrets.
The changes are largely mechanical:
- Common configuration for all ESC actions within a workflow is added to the workflow's environment variables
- Permissions are expanded as necessary for workflows that do not grant `id-token: write` permissions
- `read-all` permissions are replaced with the union of all explicit read permissions and `id-token: write`
- Default permissions are replaced with `write-all`, which is the equivalent of all explicit write permissions and
`id-token: write`
- Explicit permissions are modified to grant `id-token: write`
- A step that fetches ESC secrets and populates environment variables is added to each step that reads secrets
- Direct references to secrets …

Use ESC secrets

---

Makefile
build/Program.fs
pulumi-language-dotnet/go.mod
pulumi-language-dotnet/main.go

We currently tag this module with v3.x so its path should include `/v3.
https://go.dev/ref/mod#major-version-suffixes
> Starting with major version 2, module paths must have a major version suffix like /v2 that matches the major version. For example, if a module has the path example.com/mod at v1.0.0, it must have the path example.com/mod/v2 at version v2.0.0.

Fix invalid module path

---

.changes/unreleased/Improvements-587.yaml
sdk/Pulumi.Automation/DockerImageCredentials.cs
sdk/Pulumi.Automation/ExecutorImage.cs
sdk/Pulumi.Automation/LocalWorkspace.cs
sdk/Pulumi.Automation/LocalWorkspaceOptions.cs
sdk/Pulumi.Automation/Pulumi.Automation.xml
sdk/Pulumi.Automation/RemoteWorkspaceOptions.cs

Forgot about this one, as it wasn't listed on the ticket. This PR makes the `--remote-executor-image` flags accessible in the `dotnet` Automation API.
* https://github.com/pulumi/pulumi/pull/19286
* https://github.com/pulumi/pulumi/pull/15697
* https://github.com/pulumi/pulumi/pull/19304
Fixes https://github.com/pulumi/pulumi/issues/15693.

Expose `--remote-executor-image` in the Automation API

---

.changes/unreleased/Improvements-591.yaml
integration_tests/utils/ComponentResourceProviderBase.cs
sdk/Pulumi.Tests/Provider/PropertyValueTests.cs
sdk/Pulumi/Provider/PropertyValue.cs
sdk/Pulumi/Provider/PropertyValueSerializer.cs
sdk/Pulumi/Provider/Provider.cs
sdk/Pulumi/Pulumi.xml

This removes `OutputReference` and the nested `PropertyValue` to indicate secrets. Instead every `PropertyValue` tracks secretness and dependencies.

Update PropertyValue to match the new Go and Python SDKs

---

.changes/unreleased/Bug Fixes-595.yaml
integration_tests/resource_refs_get_resource/Program.cs
sdk/Pulumi.Tests/Mocks/MocksTests.cs
sdk/Pulumi.Tests/Mocks/TestStack.cs
sdk/Pulumi/Resources/Resource.cs
sdk/Pulumi/Serialization/OutputCompletionSource.cs

Fixes https://github.com/pulumi/pulumi-dotnet/issues/594
The base `Resource` constructor was always overwriting every `[Output]` attributed property with a new output instance that it resolved after `RegisterResource` with the data returned from that, or `unknown`. 
This doesn't make sense for local component resource which never return any properties from `RegisterResource`, and meant that assigning outputs in property initialisers (which run before constructors) would get overwritten with `unknown`.

Don't overwrite component Output properties with unknown

---

pulumi-language-dotnet/main.go

This was lint skipped in https://github.com/pulumi/pulumi-dotnet/pull/552, but we can actually just hardcode this to false now.

Remove call to GetQueryMode

---

.github/workflows/pr.yml
.github/workflows/release-sdk.yml

We should always be running the dev version of the CLI in CI when we can, both for early testing and so we can use the latest features in PRs to this repo. Update actions to always install the latest dev version.

CI: use dev version instead of latest

---

.changes/unreleased/bug-fixes-614.yaml
pulumi-language-dotnet/main.go

Follow up to https://github.com/pulumi/pulumi/pull/19216
Fixes #613

Fix gen-sdk fails if there are dangling references

---

.changes/unreleased/bug-fixes-645.yaml
.goreleaser.yml

The first attempt at this was in
https://github.com/pulumi/pulumi-dotnet/pull/635, but it didn't fix it completely.  I think this brings the .goreleaser.yml to the correct state, but only release CI will tell if I'm right.
Fixes https://github.com/pulumi/pulumi-dotnet/issues/641

try to fix release process again

---

Makefile
build/Program.fs

A conversation I had with @lunaris recently: our repositories should have common commands for common actions (code quality, changelog, release, etc). Currently, `pulumi-dotnet` has an awkward split between `Makefile` and `build/Project.fs`, and this PR is the start of an attempt to bring everything possible over to the `Makefile`. I'll leave pass-through calls in the `Project.fs` file for now so all previous commands will still work.

`Makefile` migration: `make clean`

---

Makefile
build/Program.fs

I actually already did the `Makefile` work in #631, so this is just deprecating the F# command.

`Makefile` migration: `make build_language_host`

---

.github/workflows/pr.yml
Makefile

After some discussion on Slack, here's where we are:
- `make format` will apply formatting changes and write to disk.
- `make lint` will report errors (including formatting errors) without writing to disk.
- `make format_check` will report formatting errors without writing to disk.
- `make lint_fix` will apply linting changes and write to disk.

`Makefile` migration: `make lint`/`make lint_fix`/`make format`/`make format_check`

---

.changes/unreleased/bug-fixes-667.yaml
build/Publish.fs

When publishing artifacts to NuGet, the release script currently just picks the first package it finds on the filesystem. This works fine when we know there will be exactly one, but is not robust to e.g. changes to our build process that forget to clean things up. We can of course keep alert to changes to our builds that add development artifacts, but we should probably also just make the script pickier, attempting instead to find the precise version we have been asked to publish. This change does just that.

Pick versioned artifacts when publishing

---

.changes/unreleased/Improvements-696.yaml
sdk/Pulumi.Automation/Commands/LocalPulumiCommand.cs

dotnet change to match https://github.com/pulumi/pulumi/pull/20502

Skip update checks when calling `pulumi version` in autoapi

---

.changes/unreleased/Improvements-700.yaml
sdk/Pulumi/Exceptions/LogException.cs

To help with issues like https://github.com/pulumi/pulumi-dotnet/issues/697, lets include the message from the inner exception in the LogException message so we can see what failed.

Include inner message on LogException

---

CHANGELOG_PENDING.md

We have been using changie for the changelog in this repo for a while, but never deleted the CHANGELOG_PENDING file.  It still has an old entry in there, but that's long been released already.  Just remove the file to avoid any possible confusion.

remove CHANGELOG_PENDING file
